spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5442/notification_hub
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

discord:
  webhookUrl: ""

slack:
  webhookUrl: ""

canvas:
  baseUrl: ""
  token: ""
  courseIds: [ "" ]
  pollDelayMs: 250000               # 2 minutes
  initialDelayMs: 5000              # 5 seconds on startup
