name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests-and-coverage:
    name: Tests & Coverage Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Verify Gradle wrapper exists
        run: |
          test -f notification-hub/gradlew || (echo "Missing Gradle wrapper in notification-hub/. Run 'gradle wrapper' locally and commit it." && exit 1)

      - name: Make gradlew executable
        run: chmod +x notification-hub/gradlew

      - name: Tests + coverage gate
        working-directory: notification-hub
        run: ./gradlew clean test jacocoTestReport jacocoTestCoverageVerification --no-daemon

      - name: Upload test & coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage-reports
          path: |
            notification-hub/build/reports/tests/test/**
            notification-hub/build/reports/jacoco/test/html/**
