name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Verify (tests + coverage gate)
        run: ./gradlew clean test jacocoTestReport jacocoTestCoverageVerification --no-daemon

      - name: Upload test reports (JUnit + JaCoCo HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage-reports
          path: |
            **/build/reports/tests/test/**
            **/build/reports/jacoco/test/html/**
